### ISSUE TITLE
Voting (action) buttons do not work

### ISSUE THREAD

**Issue by frdmn** [sampaiodiego/rocket.chat.app-poll#10]
I was about to try the awesome new additions by @igor9silva included in #9 and noticed the action buttons don't seem to work when using them to vote:

![untitled](https://user-images.githubusercontent.com/944459/52200204-6653f980-2868-11e9-8825-fcf1cecb99a5.gif)

Found this in the App logs (`executor` event):

#### General Information
Method: `executor`
Start Time: `2019-02-04T09:31:48.028Z`
End Time: `2019-02-04T09:31:48.037Z`
Total Time: `9ms`
Log Entries: `3`
#### Log Entries
Timestamp: `2019-02-04T09:31:48.029Z`
Severity: `debug`
Caller: `anonymous OR constructor`
Arguments: 
```
[
  "vote's executor is being executed...",
  {
    "sender": {
      "id": "fgRSWGSkthntmi8aC",
      "username": "frdmn",
      "emails": [
        {
          "address": "j@frd.mn",
          "verified": false
        }
      ],
      "type": 0,
      "isEnabled": true,
      "name": "frdmn",
      "roles": [
        "admin"
      ],
      "status": "online",
      "statusConnection": "online",
      "utcOffset": 1,
      "createdAt": "2019-02-04T08:58:57.992Z",
      "updatedAt": "2019-02-04T09:26:09.163Z",
      "lastLoginAt": "2019-02-04T09:26:09.140Z"
    },
    "room": {
      "id": "GENERAL",
      "slugifiedName": "general",
      "type": "c",
      "isDefault": true,
      "isReadOnly": false,
      "displaySystemMessages": true,
      "messageCount": 4,
      "createdAt": "2019-02-04T08:58:42.894Z",
      "updatedAt": "2019-02-04T09:25:56.461Z",
      "lastModifiedAt": "2019-02-04T09:25:56.404Z",
      "customFields": {}
    },
    "params": [
      "bdf5589d-00e0-4aef-90a3-aef0fccfbd13",
      "2"
    ]
  }
]
```
Timestamp: `2019-02-04T09:31:48.037Z`
Severity: `error`
Caller: `anonymous OR constructor`
Arguments:
```
[
  "{\"stack\":\"TypeError: RocketChat.models.Messages.getOneById is not a function
    at AppMessagesConverter.convertById (packages/rocketchat:apps/server/converters/messages.js:9:42)
    at Promise.asyncApply (packages/rocketchat:apps/server/bridges/messages.js:24:52)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\",\"message\":\"RocketChat.models.Messages.getOneById is not a function\"}"
]
```
Timestamp: `2019-02-04T09:31:48.037Z`
Severity: `debug`
Caller: `anonymous OR constructor`
Arguments: 

```
[
  "vote's executor was unsuccessful."
]
```

---

Rocket.Chat version: 0.74.0
Rocket.Chat App version: manually built using rc-apps from commit hash https://github.com/sampaiodiego/rocket.chat.app-poll/commit/2bd2c7a087e2b47b53759f3910f1fae40d23c081

**Comment by igor9silva** [comment]
Hi @frdmn,

By the error `getOneById is not a function`, I'd guess that your server doesn't have https://github.com/RocketChat/Rocket.Chat/pull/13294 merged yet, take a look at [it's changes]( https://github.com/RocketChat/Rocket.Chat/pull/13294/files).

**Comment by sampaiodiego** [comment]
that's right.. @frdmn you have to update to 0.74.1 which includes this fix. unfortunate there is no way to enforce a minimum rocket.chat version for an app
