### ISSUE TITLE
Error: Invalid index

### ISSUE THREAD

**Issue by Khaos66** [sampaiodiego/rocket.chat.app-poll#27]
I installed the latestest Rocket.Chat (2.4.0) and Poll app (Version 1.0.1) from the marketplace.
When I enter a simple poll like the following I get this error in the logs:
/poll "Question?" "Answer1" "Answer2" "Answer3" 

```
[
  "vote's executor is being executed...",
  {
    "sender": {
      "id": "xxxxxxx",
      "username": "xxxxxxx",
      "emails": [
        {
          "address": "xxxxxxxx",
          "verified": false
        }
      ],
      "type": 0,
      "isEnabled": true,
      "name": "xxxxxxxxx",
      "roles": [
        "admin"
      ],
      "status": "online",
      "statusConnection": "online",
      "utcOffset": 9,
      "createdAt": "2020-01-08T05:43:30.856Z",
      "updatedAt": "2020-01-09T02:21:50.731Z",
      "lastLoginAt": "2020-01-09T02:21:50.731Z"
    },
    "room": {
      "id": "xxxxxxxx",
      "type": "d",
      "isDefault": false,
      "isReadOnly": false,
      "displaySystemMessages": true,
      "messageCount": 16,
      "createdAt": "2020-01-08T13:30:57.556Z",
      "updatedAt": "2020-01-09T02:19:35.104Z",
      "lastModifiedAt": "2020-01-09T02:19:35.070Z"
    },
    "params": [
      "\"Question?\"",
      "\"Answer1\"",
      "\"Answer2\"",
      "\"Answer3\""
    ]
  }
]
```

```
[
  "{\"stack\":\"Error: Invalid index
    at VoteCommand.executor (evalmachine.<anonymous>:24:19)
    at evalmachine.<anonymous>:1:-39
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at Object.runInContext (vm.js:120:6)
    at ProxiedApp.runInContext (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/ProxiedApp.js:54:19)
    at AppSlashCommand.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/managers/AppSlashCommand.js:62:41)
    at Generator.next (<anonymous>)
    at /opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/managers/AppSlashCommand.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/managers/AppSlashCommand.js:3:12)\",\"message\":\"Invalid index\"}"
]
```

**Comment by sampaiodiego** [comment]
thanks for reporting.

I have a question though, are you sure you're using `/poll` command? because the log says `vote's executor is being executed` and it the log showed when you use `/vote` command.

**Comment by sampaiodiego** [comment]
there is other error preventing poll creations on rocket.chat 2.4.0 though.. I'm working on a fix already

**Comment by Khaos66** [comment]
You're right! Maybe I tried /vote after /poll wasn't working. Sorry.

**Comment by Khaos66** [comment]
After upgrading Rocket.Chat to version 2.4.1 the /poll command works again. You may close the issue now.

**Comment by sampaiodiego** [comment]
thanks @Khaos66 for letting me know.. I was about to comment that upgrading Rocket.Chat should fix the issue =)
