### ISSUE TITLE
Not enough permission

### ISSUE THREAD

**Issue by Monschichi** [sampaiodiego/rocket.chat.app-poll#72]
After upgrading Rocket.Chat to 3.15.0, and still in 3.16.0 polls aren't working in private channels.

When creating a poll and clicking on the `Create` button nothing happens.

The post to https://DOMAIN/api/apps/ui.interaction/c33fa1a6-68a7-491e-bf49-9d7b99671c48 returns: `{"appId":"c33fa1a6-68a7-491e-bf49-9d7b99671c48","triggerId":"KFNPFPu2K9TmNHcFa","success":false,"type":"errors","viewId":"5ac7f4cb-80e3-43d7-8eb5-bb19e38f129d","errors":{}}`
Rocket.Chat Logs shows:
```
Jul 01 08:43:01 host rocketchat[23993]: server.js:204 System ➔ error Error sending message: Error: Not enough permission
Jul 01 08:43:01 host rocketchat[23993]:     at validateMessage (app/lib/server/functions/sendMessage.js:151:10)
Jul 01 08:43:01 host rocketchat[23993]:     at sendMessage (app/lib/server/functions/sendMessage.js:165:2)
Jul 01 08:43:01 host rocketchat[23993]:     at executeSendMessage (app/lib/server/methods/sendMessage.js:79:10)
Jul 01 08:43:01 host rocketchat[23993]:     at app/apps/server/bridges/messages.ts:25:23
Jul 01 08:43:01 host rocketchat[23993]:     at /rocket.chat-v3.16.0/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

Versions:
Rocket.Chat: 3.16.0
Poll: 2.0.0

**Comment by devi4nt** [comment]
We're experiencing the same issue, any ideas when there will be a fix / is there a potential work around?
